/* Auto-generated by scripts/process-icons.mjs — do not edit. */
import type { ComponentType } from 'react';
import type { IconName } from './manifest';
import { GridFill } from './generated/grid-fill';
import { ReceiptFill } from './generated/receipt-fill';
import { BuildingFill } from './generated/building-fill';
import { ShieldFillCheck } from './generated/shield-fill-check';
import { FileEarmarkTextFill } from './generated/file-earmark-text-fill';
import { BarChartFill } from './generated/bar-chart-fill';
import { GearFill } from './generated/gear-fill';
import { HouseFill } from './generated/house-fill';
import { Plus } from './generated/plus';
import { Search } from './generated/search';
import { FunnelFill } from './generated/funnel-fill';
import { DownloadFill } from './generated/download-fill';
import { UploadFill } from './generated/upload-fill';
import { PencilFill } from './generated/pencil-fill';
import { TrashFill } from './generated/trash-fill';
import { ClipboardFill } from './generated/clipboard-fill';
import { ThreeDotsVertical } from './generated/three-dots-vertical';
import { X } from './generated/x';
import { Check } from './generated/check';
import { ArrowRight } from './generated/arrow-right';
import { ArrowLeft } from './generated/arrow-left';
import { ChevronRight } from './generated/chevron-right';
import { ChevronDown } from './generated/chevron-down';
import { EnvelopeFill } from './generated/envelope-fill';
import { TelephoneFill } from './generated/telephone-fill';
import { GeoAltFill } from './generated/geo-alt-fill';
import { CheckCircleFill } from './generated/check-circle-fill';
import { XCircleFill } from './generated/x-circle-fill';
import { ClockFill } from './generated/clock-fill';
import { BellFill } from './generated/bell-fill';
import { MoonFill } from './generated/moon-fill';
import { SunFill } from './generated/sun-fill';
import { PersonCircleFill } from './generated/person-circle-fill';
import { BoxArrowRightFill } from './generated/box-arrow-right-fill';
import { FilmFill } from './generated/film-fill';
import { TruckFill } from './generated/truck-fill';
import { ScissorsFill } from './generated/scissors-fill';
import type { IconComponentProps } from './generated/grid-fill';

export const ICON_COMPONENTS: Record<IconName, ComponentType<IconComponentProps>> = {
  'grid-fill': GridFill,
  'receipt-fill': ReceiptFill,
  'building-fill': BuildingFill,
  'shield-fill-check': ShieldFillCheck,
  'file-earmark-text-fill': FileEarmarkTextFill,
  'bar-chart-fill': BarChartFill,
  'gear-fill': GearFill,
  'house-fill': HouseFill,
  'plus': Plus,
  'search': Search,
  'funnel-fill': FunnelFill,
  'download-fill': DownloadFill,
  'upload-fill': UploadFill,
  'pencil-fill': PencilFill,
  'trash-fill': TrashFill,
  'clipboard-fill': ClipboardFill,
  'three-dots-vertical': ThreeDotsVertical,
  'x': X,
  'check': Check,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'envelope-fill': EnvelopeFill,
  'telephone-fill': TelephoneFill,
  'geo-alt-fill': GeoAltFill,
  'check-circle-fill': CheckCircleFill,
  'x-circle-fill': XCircleFill,
  'clock-fill': ClockFill,
  'bell-fill': BellFill,
  'moon-fill': MoonFill,
  'sun-fill': SunFill,
  'person-circle-fill': PersonCircleFill,
  'box-arrow-right-fill': BoxArrowRightFill,
  'film-fill': FilmFill,
  'truck-fill': TruckFill,
  'scissors-fill': ScissorsFill,
};

export type { IconName } from './manifest';
export type { IconComponentProps } from './generated/grid-fill';
