#!/usr/bin/env node
/**
 * Icon build pipeline.
 *
 * 1. Reads the list of icon names from src/icons/manifest.ts.
 * 2. For each name, copies the SVG from the Bootsy Duotone archive to
 *    src/icons/source/ (vendored — reproducible without the user's Downloads).
 * 3. Transforms each SVG into a typed React component at src/icons/generated/.
 *    - `fill="black"` → `fill="currentColor"` so icons follow text colour.
 *    - kebab-case SVG attributes → camelCase JSX attributes.
 *    - Wrapped in a component that accepts `size` + SVGProps.
 * 4. Regenerates src/icons/index.ts with the name → component map used by <Icon/>.
 *
 * Re-run after adding names to manifest.ts.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..');

const BOOTSY_SOURCE = '/Users/josepbordesjove/Downloads/Bootsy Duotone/SVG/All icons';
const VENDOR_DIR = path.join(repoRoot, 'src/icons/source');
const GENERATED_DIR = path.join(repoRoot, 'src/icons/generated');
const MANIFEST_FILE = path.join(repoRoot, 'src/icons/manifest.ts');
const INDEX_FILE = path.join(repoRoot, 'src/icons/index.ts');

function toPascalCase(name) {
  return name.split('-').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}

async function readManifest() {
  const src = await fs.readFile(MANIFEST_FILE, 'utf8');
  const match = src.match(/ICON_NAMES\s*=\s*\[([\s\S]*?)\]\s*as const/);
  if (!match) throw new Error('Could not parse ICON_NAMES from manifest.ts');
  return match[1]
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.startsWith("'"))
    .map((l) => l.replace(/^'([^']+)'.*/, '$1'));
}

function transformSvgToJsx(svg) {
  // Strip the outer <svg ...> wrapper — we'll rebuild it with props.
  const innerMatch = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!innerMatch) throw new Error('SVG has no inner content');
  let inner = innerMatch[1].trim();

  // Black → currentColor so the icon follows the current text colour.
  inner = inner.replace(/fill="black"/g, 'fill="currentColor"');
  inner = inner.replace(/stroke="black"/g, 'stroke="currentColor"');

  // Convert kebab-case SVG attributes to camelCase for JSX.
  const kebabAttrs = [
    'fill-rule',
    'clip-rule',
    'fill-opacity',
    'stroke-width',
    'stroke-linecap',
    'stroke-linejoin',
    'stroke-opacity',
    'stroke-dasharray',
    'stroke-miterlimit',
  ];
  for (const attr of kebabAttrs) {
    const camel = attr.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    inner = inner.replace(new RegExp(attr + '=', 'g'), camel + '=');
  }

  // Self-close any <path ...> / <circle ...> / <rect ...> / <polygon ...> tags
  // that ended with ` />` — they're already JSX-safe in the source, keep as-is.
  return inner;
}

function emitComponent(name, inner) {
  const componentName = toPascalCase(name);
  return `import type { SVGProps } from 'react';

export interface IconComponentProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function ${componentName}({ size = 16, ...props }: IconComponentProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      ${inner.replace(/\n/g, '\n      ')}
    </svg>
  );
}
`;
}

async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

async function writeIndex(names, pascalByName) {
  const imports = names
    .map((n) => `import { ${pascalByName[n]} } from './generated/${n}';`)
    .join('\n');

  const entries = names
    .map((n) => `  '${n}': ${pascalByName[n]},`)
    .join('\n');

  const body = `/* Auto-generated by scripts/process-icons.mjs — do not edit. */
import type { ComponentType } from 'react';
import type { IconName } from './manifest';
${imports}
import type { IconComponentProps } from './generated/${names[0]}';

export const ICON_COMPONENTS: Record<IconName, ComponentType<IconComponentProps>> = {
${entries}
};

export type { IconName } from './manifest';
export type { IconComponentProps } from './generated/${names[0]}';
`;
  await fs.writeFile(INDEX_FILE, body, 'utf8');
}

async function main() {
  await ensureDir(VENDOR_DIR);
  await ensureDir(GENERATED_DIR);

  const names = await readManifest();
  console.log(`[icons] ${names.length} names in manifest`);

  const pascalByName = {};
  let ok = 0;
  let missing = 0;

  for (const name of names) {
    const sourceSvgPath = path.join(BOOTSY_SOURCE, `${name}.svg`);
    let raw;
    try {
      raw = await fs.readFile(sourceSvgPath, 'utf8');
    } catch {
      console.warn(`[icons] missing in Bootsy archive: ${name}`);
      missing += 1;
      continue;
    }

    // Vendor (copy) into src/icons/source/
    await fs.writeFile(path.join(VENDOR_DIR, `${name}.svg`), raw, 'utf8');

    // Transform + write .tsx
    const inner = transformSvgToJsx(raw);
    const tsx = emitComponent(name, inner);
    pascalByName[name] = toPascalCase(name);
    await fs.writeFile(path.join(GENERATED_DIR, `${name}.tsx`), tsx, 'utf8');

    ok += 1;
  }

  // Filter manifest down to successfully built icons for the index map.
  const built = names.filter((n) => pascalByName[n]);
  await writeIndex(built, pascalByName);

  console.log(`[icons] built ${ok}/${names.length}${missing ? ` (${missing} missing)` : ''}`);
  console.log(`[icons] wrote ${GENERATED_DIR}`);
}

await main();
